### PR TITLE
feat: implemented create event route

### LINKED ISSUE #33: 💡Feature: Events route for creating an event
### Description

With the event schema made, a route must be set up that is responsible for adding an event. It would take in all the needed details and create an event in the database. 

Also add documentation for the same, in [Api.yaml file](https://github.com/MilanCommunity/Milan-Backend/blob/main/config/api.yaml) the documentation would be better for folks who are getting started.

### Screenshots

_No response_

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan-Backend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan-Backend/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

### PR DESCRIPTION
**Pull request by MahendraDani**
closes #33 

### 👷🏻 Changes made  

1. Implemented create event route as per given `Event Schema`
2. Added status codes and status messages in `utils/status.js` file to improve code usability.
3. Added documentation of the route in `api.yaml` file.

- I have tested my code locally and it works as expected without any errors.

### CODE REVIEW

**Comment by tamalCodes** [comment]
Looks good, can you perhaps do a screen recording and show how the API is working ?
That will save me from having to setup the code again and test it manually.

**Comment by MahendraDani** [comment]
> Looks good, can you perhaps do a screen recording and show how the API is working ?
> That will save me from having to setup the code again and test it manually.

Sure!

**Comment by MahendraDani** [comment]
## API Working
https://github.com/MilanCommunity/Milan-Backend/assets/116940083/5b36a501-0517-433a-8932-c2b425eadc38

- The above screen recording shows the working of the API.

## Database view

https://github.com/MilanCommunity/Milan-Backend/assets/116940083/34fd89ee-88ab-43c1-bc40-9a8a906af7ca

- The above screen recording shows that the data is also successfully stored in the database.

@tamalCodes If there are any other changes please let me know

**Comment by tamalCodes** [comment]
Hi @MahendraDani , the changes look amazing to me. Just a thought, wouldn't it be better if the `createdAt` and `updatedAt` would have been populated automatically based on the current time instead of us filling in the date and time manually ?

**Comment by MahendraDani** [comment]
> Hi @MahendraDani , the changes look amazing to me. Just a thought, wouldn't it be better if the `createdAt` and `updatedAt` would have been populated automatically based on the current time instead of us filling in the date and time manually ? 

@tamalCodes 
Yes you are right!
I will implement that. 
Please tell me the format of date?
Like dd-mm-yy or different

**Comment by MahendraDani** [comment]
@tamalCodes 
I made the required changes. Now time is dynamically added to `createdAt` and `updatedAt` props in https://github.com/MilanCommunity/Milan-Backend/pull/39/commits/068ea0c201ad8fbbf715799b8e7d870d2f8137db

Screen Recording of API testing

https://github.com/MilanCommunity/Milan-Backend/assets/116940083/1abb20bd-4af7-4b17-93db-eff06a9f7bce

**Review by tamalCodes — APPROVED** [review]
# Amazing work 🎉
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/MilanCommunity/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

**Pull request merged**
